packages:
  - .

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild

blockExoticSubdeps: true

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@usehercules/*"
allowBuilds:
  "@swc/core": true
  esbuild: true
