/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type DocumentStatus = "approved" | "converted" | "declined" | "draft" | "expired" | "sent" | "signed" | "viewed" | "voided";

export type DocumentType = "certificate_of_completion" | "change_order" | "contract" | "estimate" | "work_order";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type InvitationStatus = "accepted" | "cancelled" | "expired" | "pending";

export type JobStatusCategory = "active" | "canceled" | "completed" | "on_hold" | "planned";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrgRole = "admin" | "manager" | "sales";

export type PipelineType = "lead" | "opportunity";

export type PlatformRole = "super_admin" | "user";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLog {
  action: string;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  orgId: number | null;
  recordId: string | null;
  recordType: string | null;
  userId: number | null;
}

export interface Contacts {
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  customerId: number;
  email: string | null;
  firstName: string;
  id: Generated<number>;
  isDeleted: Generated<boolean | null>;
  isPrimary: Generated<boolean | null>;
  lastName: string | null;
  orgId: number;
  phone: string | null;
  title: string | null;
}

export interface Customers {
  address: string | null;
  city: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  email: string | null;
  id: Generated<number>;
  isDeleted: Generated<boolean | null>;
  name: string;
  notes: string | null;
  orgId: number;
  phone: string | null;
  state: string | null;
  type: Generated<string | null>;
  updatedAt: Generated<Timestamp | null>;
  zip: string | null;
}

export interface DocumentEmailLog {
  documentId: number;
  emailMessageId: string | null;
  id: Generated<number>;
  message: string | null;
  orgId: number;
  recipientEmail: string;
  senderEmail: string;
  sentAt: Generated<Timestamp>;
  sentBy: number | null;
  subject: string | null;
  versionNumber: number;
}

export interface DocumentLineItems {
  category: string | null;
  description: Generated<string>;
  documentId: number;
  id: Generated<number>;
  lineTotal: Generated<Numeric>;
  notes: string | null;
  orgId: number;
  quantity: Generated<Numeric>;
  sortOrder: Generated<number>;
  unit: string | null;
  unitPrice: Generated<Numeric>;
}

export interface DocumentReviewLinks {
  allowPdfDownload: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  createdBy: number | null;
  documentId: number;
  expiresAt: Timestamp | null;
  id: Generated<number>;
  isRevoked: Generated<boolean>;
  orgId: number;
  revokedAt: Timestamp | null;
  revokedBy: number | null;
  tokenHash: string;
  versionNumber: number;
  viewedAt: Timestamp | null;
}

export interface DocumentSignatures {
  documentId: number;
  id: Generated<number>;
  ipAddress: string | null;
  orgId: number;
  signatureData: string;
  signedAt: Generated<Timestamp>;
  signerEmail: string | null;
  signerName: string;
  signerRole: Generated<string>;
  versionNumber: number;
}

export interface DocumentTemplates {
  blocks: Generated<Json>;
  createdAt: Generated<Timestamp>;
  createdBy: number | null;
  documentType: DocumentType;
  id: Generated<number>;
  isActive: Generated<boolean>;
  isFoundation: Generated<boolean>;
  name: string;
  orgId: number | null;
  settings: Generated<Json>;
  updatedAt: Generated<Timestamp>;
}

export interface DocumentVersionSnapshots {
  blocksSnapshot: Json;
  createdAt: Generated<Timestamp>;
  createdBy: number | null;
  dataSnapshot: Generated<Json>;
  discount: Numeric | null;
  documentId: number;
  id: Generated<number>;
  lineItemsSnapshot: Json | null;
  notes: string | null;
  pdfStorageKey: string | null;
  settingsSnapshot: Generated<Json>;
  status: DocumentStatus;
  subtotal: Numeric | null;
  tax: Numeric | null;
  total: Numeric | null;
  versionNumber: number;
}

export interface FeatureFlags {
  enabled: Generated<boolean | null>;
  flagName: string;
  id: Generated<number>;
  orgId: number;
}

export interface JobActivityEvents {
  createdAt: Generated<Timestamp | null>;
  description: string;
  eventType: string;
  id: Generated<number>;
  jobId: number;
  metadata: string | null;
  orgId: number;
  userId: number | null;
}

export interface JobAppointments {
  assignedTo: number | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  duration: Generated<number | null>;
  id: Generated<number>;
  jobId: number;
  location: string | null;
  notes: string | null;
  orgId: number;
  scheduledAt: Timestamp;
  title: string;
}

export interface JobAssignments {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  jobId: number;
  orgId: number;
  userId: number;
}

export interface JobContacts {
  contactId: number;
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  id: Generated<number>;
  jobId: number;
  orgId: number;
}

export interface JobDocuments {
  approvalComment: string | null;
  approvalIp: string | null;
  approvedAmount: Numeric | null;
  approvedAt: Timestamp | null;
  approverEmail: string | null;
  approverName: string | null;
  blocksSnapshot: Generated<Json>;
  createdAt: Generated<Timestamp>;
  createdBy: number | null;
  customerId: number | null;
  dataSnapshot: Generated<Json>;
  declinedAt: Timestamp | null;
  declinedByEmail: string | null;
  declinedByName: string | null;
  declineReason: string | null;
  discount: Numeric | null;
  documentNumber: string;
  documentType: DocumentType;
  id: Generated<number>;
  isSigned: Generated<boolean>;
  jobId: number | null;
  notes: string | null;
  opportunityId: number | null;
  orgId: number;
  pdfStorageKey: string | null;
  propertyId: number | null;
  sentAt: Timestamp | null;
  settingsSnapshot: Generated<Json>;
  signedAt: Timestamp | null;
  signedPdfStorageKey: string | null;
  status: Generated<DocumentStatus>;
  subtotal: Numeric | null;
  tax: Numeric | null;
  templateId: number | null;
  templateVersionNumber: number | null;
  total: Numeric | null;
  updatedAt: Generated<Timestamp>;
  versionNumber: Generated<number>;
  viewedAt: Timestamp | null;
  voidedAt: Timestamp | null;
  voidedBy: number | null;
  voidReason: string | null;
}

export interface JobFiles {
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  fileName: string;
  fileSize: Int8 | null;
  id: Generated<number>;
  jobId: number;
  mimeType: string | null;
  orgId: number;
  storageKey: string;
}

export interface JobInsurance {
  adjusterEmail: string | null;
  adjusterName: string | null;
  adjusterPhone: string | null;
  carrier: string | null;
  carrierEmail: string | null;
  carrierPhone: string | null;
  claimNumber: string | null;
  coverageType: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  dateOfLoss: Timestamp | null;
  deductible: Numeric | null;
  id: Generated<number>;
  jobId: number;
  orgId: number;
  policyNumber: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface JobNotes {
  content: string;
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  id: Generated<number>;
  jobId: number;
  orgId: number;
}

export interface JobPhotos {
  caption: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  id: Generated<number>;
  jobId: number;
  orgId: number;
  storageKey: string;
}

export interface Jobs {
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  customerId: number | null;
  estimatedValue: Numeric | null;
  id: Generated<number>;
  isDeleted: Generated<boolean | null>;
  isInsuranceJob: Generated<boolean | null>;
  jobType: string | null;
  name: string;
  needsReview: Generated<boolean | null>;
  nextStep: string | null;
  notes: string | null;
  opportunityId: number | null;
  orgId: number;
  propertyId: number | null;
  startDate: Timestamp | null;
  status: Generated<string | null>;
  targetCompletionDate: Timestamp | null;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: number | null;
}

export interface JobStatuses {
  category: Generated<JobStatusCategory>;
  color: Generated<string | null>;
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  id: Generated<number>;
  isArchived: Generated<boolean | null>;
  isDefault: Generated<boolean | null>;
  name: string;
  orgId: number;
  sortOrder: Generated<number>;
}

export interface JobTasks {
  assignedTo: number | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  description: string | null;
  dueDate: Timestamp | null;
  id: Generated<number>;
  isCompleted: Generated<boolean | null>;
  jobId: number;
  orgId: number;
  title: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface Leads {
  assignedTo: number | null;
  contactId: number | null;
  convertedOpportunityId: number | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  customerId: number | null;
  estimatedValue: Numeric | null;
  id: Generated<number>;
  isConverted: Generated<boolean | null>;
  isDeleted: Generated<boolean | null>;
  name: string;
  notes: string | null;
  orgId: number;
  propertyId: number | null;
  source: string | null;
  stageId: number | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface Opportunities {
  assignedTo: number | null;
  contactId: number | null;
  convertedJobId: number | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  customerId: number | null;
  expectedCloseDate: Timestamp | null;
  id: Generated<number>;
  isDeleted: Generated<boolean | null>;
  isWon: Generated<boolean | null>;
  leadId: number | null;
  name: string;
  notes: string | null;
  orgId: number;
  propertyId: number | null;
  stageId: number | null;
  updatedAt: Generated<Timestamp | null>;
  value: Numeric | null;
}

export interface Organizations {
  address: string | null;
  city: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  email: string | null;
  id: Generated<number>;
  isDeleted: Generated<boolean | null>;
  logoUrl: string | null;
  name: string;
  phone: string | null;
  plan: Generated<string | null>;
  primaryColor: Generated<string | null>;
  secondaryColor: Generated<string | null>;
  slug: string;
  state: string | null;
  status: Generated<string | null>;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: number | null;
  website: string | null;
  zip: string | null;
}

export interface OrgInvitations {
  createdAt: Generated<Timestamp | null>;
  email: string;
  expiresAt: Timestamp;
  id: Generated<number>;
  invitedBy: number | null;
  orgId: number;
  role: Generated<OrgRole>;
  status: Generated<InvitationStatus>;
  token: string;
}

export interface OrgMemberships {
  id: Generated<number>;
  joinedAt: Generated<Timestamp | null>;
  orgId: number;
  role: Generated<OrgRole>;
  status: Generated<string | null>;
  userId: number;
}

export interface OrgSettings {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  orgId: number;
  recordVisibilityPolicy: Generated<string | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface PipelineStages {
  color: Generated<string | null>;
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  id: Generated<number>;
  isArchived: Generated<boolean | null>;
  isDefault: Generated<boolean | null>;
  name: string;
  orgId: number;
  pipelineType: PipelineType;
  sortOrder: Generated<number>;
}

export interface Properties {
  address: string;
  city: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  customerId: number;
  id: Generated<number>;
  isDeleted: Generated<boolean | null>;
  name: string | null;
  orgId: number;
  propertyType: string | null;
  state: string | null;
  zip: string | null;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  currentOrgId: number | null;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface TemplateVersions {
  blocks: Json;
  createdAt: Generated<Timestamp>;
  createdBy: number | null;
  id: Generated<number>;
  name: string;
  notes: string | null;
  settings: Generated<Json>;
  templateId: number;
  versionNumber: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  lastOrgId: number | null;
  role: Generated<PlatformRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  auditLog: AuditLog;
  contacts: Contacts;
  customers: Customers;
  documentEmailLog: DocumentEmailLog;
  documentLineItems: DocumentLineItems;
  documentReviewLinks: DocumentReviewLinks;
  documentSignatures: DocumentSignatures;
  documentTemplates: DocumentTemplates;
  documentVersionSnapshots: DocumentVersionSnapshots;
  featureFlags: FeatureFlags;
  jobActivityEvents: JobActivityEvents;
  jobAppointments: JobAppointments;
  jobAssignments: JobAssignments;
  jobContacts: JobContacts;
  jobDocuments: JobDocuments;
  jobFiles: JobFiles;
  jobInsurance: JobInsurance;
  jobNotes: JobNotes;
  jobPhotos: JobPhotos;
  jobs: Jobs;
  jobStatuses: JobStatuses;
  jobTasks: JobTasks;
  leads: Leads;
  loginAttempts: LoginAttempts;
  opportunities: Opportunities;
  organizations: Organizations;
  orgInvitations: OrgInvitations;
  orgMemberships: OrgMemberships;
  orgSettings: OrgSettings;
  pipelineStages: PipelineStages;
  properties: Properties;
  sessions: Sessions;
  templateVersions: TemplateVersions;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const PlatformRoleArrayValues: [PlatformRole, ...PlatformRole[]] = ["super_admin","user"];
export const OrgRoleArrayValues: [OrgRole, ...OrgRole[]] = ["admin","manager","sales"];
export const InvitationStatusArrayValues: [InvitationStatus, ...InvitationStatus[]] = ["accepted","cancelled","expired","pending"];
export const PipelineTypeArrayValues: [PipelineType, ...PipelineType[]] = ["lead","opportunity"];
export const JobStatusCategoryArrayValues: [JobStatusCategory, ...JobStatusCategory[]] = ["active","canceled","completed","on_hold","planned"];
export const DocumentTypeArrayValues: [DocumentType, ...DocumentType[]] = ["certificate_of_completion","change_order","contract","estimate","work_order"];
export const DocumentStatusArrayValues: [DocumentStatus, ...DocumentStatus[]] = ["approved","converted","declined","draft","expired","sent","signed","viewed","voided"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.