import type { VentProduct } from "./types";

/**
 * Typical manufacturer net-free-area values compiled from published product
 * literature (GAF / Air Vent, Owens Corning, Cor-A-Vent, Lomanco, ARMA).
 * Always verify against the NFA stamped on the actual product.
 */
export const VENT_CATALOG: VentProduct[] = [
  {
    id: "cont-soffit",
    name: "Continuous soffit vent",
    shortName: "Cont. soffit",
    role: "intake",
    unit: "lf",
    nfa: 9,
    sizeNote: "9 sq in / lf typical perforated vinyl or aluminum",
    source: "Common vinyl/aluminum soffit panels; some profiles are only 4–6 sq in/lf",
    mixGroup: "soffit",
  },
  {
    id: "soffit-16x8",
    name: "16 × 8 in. soffit vent",
    shortName: "16×8 soffit",
    role: "intake",
    unit: "each",
    nfa: 56,
    sizeNote: "56 sq in NFA typical screened metal under-eave",
    source: "Air Vent / generic 16×8 rectangular soffit, screened",
    mixGroup: "soffit",
  },
  {
    id: "soffit-16x4",
    name: "16 × 4 in. soffit vent",
    shortName: "16×4 soffit",
    role: "intake",
    unit: "each",
    nfa: 18,
    sizeNote: "18 sq in NFA typical",
    source: "Metal 16×4 under-eave soffit",
    mixGroup: "soffit",
  },
  {
    id: "soffit-round-4",
    name: "4 in. round soffit vent",
    shortName: "4 in. round",
    role: "intake",
    unit: "each",
    nfa: 12,
    sizeNote: "12 sq in NFA typical recessed round",
    source: "Recessed round soffit inserts",
    mixGroup: "soffit",
  },
  {
    id: "soffit-round-6",
    name: "6 in. round soffit vent",
    shortName: "6 in. round",
    role: "intake",
    unit: "each",
    nfa: 18,
    sizeNote: "18 sq in NFA typical",
    source: "Recessed round soffit inserts",
    mixGroup: "soffit",
  },
  {
    id: "drip-edge",
    name: "Drip-edge / starter eave vent",
    shortName: "Starter eave",
    role: "intake",
    unit: "lf",
    nfa: 9,
    sizeNote: "9 sq in / lf typical (Air Vent The Edge class)",
    source: "Drip-edge intake / starter-strip eave vents",
    mixGroup: "drip",
  },
  {
    id: "ridge-18",
    name: "Shingle-over ridge vent (18 NFA)",
    shortName: "Ridge 18",
    role: "exhaust",
    unit: "lf",
    nfa: 18,
    sizeNote: "18 sq in / lf — most common shingle-over ridge",
    source: "GAF Cobra Ridge Runner, OC VentSure, similar",
    mixGroup: "ridge",
  },
  {
    id: "ridge-12",
    name: "Filtered ridge vent (12 NFA)",
    shortName: "Ridge 12",
    role: "exhaust",
    unit: "lf",
    nfa: 12,
    sizeNote: "12 sq in / lf conservative / snow-filter products",
    source: "Some filtered or low-profile ridge vents",
    mixGroup: "ridge",
  },
  {
    id: "ridge-20",
    name: "High-capacity ridge vent (20 NFA)",
    shortName: "Ridge 20",
    role: "exhaust",
    unit: "lf",
    nfa: 20,
    sizeNote: "20 sq in / lf (Cor-A-Vent V-600 class)",
    source: "Cor-A-Vent V-600 and similar high-capacity ridge",
    mixGroup: "ridge",
  },
  {
    id: "off-ridge",
    name: "Off-ridge static vent",
    shortName: "Off-ridge",
    role: "exhaust",
    unit: "each",
    nfa: 50,
    sizeNote: "50 sq in NFA typical near-ridge box vent",
    source: "Static off-ridge / near-ridge vents",
    mixGroup: "offridge",
  },
  {
    id: "dome-50",
    name: "Dome / box / turtle vent",
    shortName: "Dome 50",
    role: "exhaust",
    unit: "each",
    nfa: 50,
    sizeNote: "50 sq in NFA typical roof louver",
    source: "Round-top or square roof louvers",
    mixGroup: "dome",
  },
  {
    id: "dome-144",
    name: "Large dome / roof louver",
    shortName: "Dome 144",
    role: "exhaust",
    unit: "each",
    nfa: 144,
    sizeNote: "144 sq in NFA large static dome",
    source: "Large roof louvers",
    mixGroup: "dome",
  },
  {
    id: "gable-12x12",
    name: "Gable louver 12 × 12 in.",
    shortName: "Gable 12×12",
    role: "exhaust",
    unit: "each",
    nfa: 50,
    sizeNote: "50 sq in NFA after louvers + screen (144 gross)",
    source: "Typical residential gable louver",
    mixGroup: "gable",
  },
  {
    id: "gable-12x18",
    name: "Gable louver 12 × 18 in.",
    shortName: "Gable 12×18",
    role: "exhaust",
    unit: "each",
    nfa: 80,
    sizeNote: "80 sq in NFA typical",
    source: "Typical residential gable louver",
    mixGroup: "gable",
  },
  {
    id: "gable-18x24",
    name: "Gable louver 18 × 24 in.",
    shortName: "Gable 18×24",
    role: "exhaust",
    unit: "each",
    nfa: 140,
    sizeNote: "140 sq in NFA typical",
    source: "Typical residential gable louver",
    mixGroup: "gable",
  },
  {
    id: "gable-24x30",
    name: "Gable louver 24 × 30 in.",
    shortName: "Gable 24×30",
    role: "exhaust",
    unit: "each",
    nfa: 230,
    sizeNote: "230 sq in NFA typical",
    source: "Typical residential gable louver",
    mixGroup: "gable",
  },
  {
    id: "turbine-12",
    name: "12 in. wind turbine",
    shortName: "Turbine 12",
    role: "exhaust",
    unit: "each",
    nfa: 50,
    sizeNote: "50 sq in static NFA (higher when spinning)",
    source: "Lomanco-class 12 in. turbine gravity rating",
    mixGroup: "turbine",
  },
  {
    id: "turbine-14",
    name: "14 in. wind turbine",
    shortName: "Turbine 14",
    role: "exhaust",
    unit: "each",
    nfa: 80,
    sizeNote: "80 sq in static NFA (higher when spinning)",
    source: "Lomanco-class 14 in. turbine gravity rating",
    mixGroup: "turbine",
  },
  {
    id: "solar-fan",
    name: "Solar-powered attic fan",
    shortName: "Solar fan",
    role: "mechanical",
    unit: "each",
    nfa: 0,
    cfm: 1000,
    sizeNote: "Mechanical CFM — does not count as IRC net free area",
    source: "HVI-style sizing 0.7 CFM/sq ft; makeup air 1 sq ft per 300 CFM",
    mixGroup: "fan",
  },
  {
    id: "electric-fan",
    name: "Electric powered attic fan",
    shortName: "Electric fan",
    role: "mechanical",
    unit: "each",
    nfa: 0,
    cfm: 1200,
    sizeNote: "Mechanical CFM — does not count as IRC net free area",
    source: "HVI-style sizing 0.7 CFM/sq ft; makeup air 1 sq ft per 300 CFM",
    mixGroup: "fan",
  },
  {
    id: "custom-intake",
    name: "Custom intake vent",
    shortName: "Custom intake",
    role: "intake",
    unit: "each",
    nfa: 50,
    sizeNote: "Enter the manufacturer NFA from the product label",
    source: "User-supplied NFA",
    mixGroup: "custom",
  },
  {
    id: "custom-exhaust",
    name: "Custom exhaust vent",
    shortName: "Custom exhaust",
    role: "exhaust",
    unit: "each",
    nfa: 50,
    sizeNote: "Enter the manufacturer NFA from the product label",
    source: "User-supplied NFA",
    mixGroup: "custom",
  },
];

export const CATALOG_BY_ID: Record<string, VentProduct> = Object.fromEntries(
  VENT_CATALOG.map((p) => [p.id, p]),
);

export const INTAKE_PRODUCTS = VENT_CATALOG.filter((p) => p.role === "intake");
export const EXHAUST_PRODUCTS = VENT_CATALOG.filter((p) => p.role === "exhaust");
export const MECHANICAL_PRODUCTS = VENT_CATALOG.filter((p) => p.role === "mechanical");

export const CLIMATE_ZONE_HINTS: Record<number, string> = {
  1: "S. Florida, Hawaii",
  2: "Gulf Coast, S. Texas",
  3: "N. Texas, Georgia, Carolinas",
  4: "Mid-Atlantic, Pacific NW",
  5: "Lower Midwest, S. New England",
  6: "Upper Midwest, N. New England",
  7: "N. Minnesota, N. Maine",
  8: "Interior Alaska",
};

export const DEFAULT_PROJECT_NAME = "Untitled attic";
